apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/expose-istiod: "15012"
    topology.istio.io/network: eks # Must match istioctl install command
  # annotations:
    # networking.istio.io/service-type: NodePort
    # istio.io/expose-gateway-address: "rvennam-exs-lb-69407821cce3a017.elb.us-east-1.amazonaws.com"
  name: eastwest
  namespace: istio-system
spec:
  gatewayClassName: istio-eastwest
  listeners:
  - name: cross-network
    port: 15008
    protocol: HBONE
    tls:
      mode: Passthrough
  - name: xds-tls
    port: 15012
    protocol: TLS
    tls:
      mode: Passthrough
