apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: \"${EKS_VERSION}\"
  tags:
    owner: ${OWNER_NAME}

addons:
  - name: vpc-cni # Addon to enable networking for the cluster
  - name: eks-pod-identity-agent # Enables pod identity management for ECS workloads

iam:
  withOIDC: true # Required to use IAM roles for service accounts
  podIdentityAssociations:
    - namespace: istio-system # Namespace for Istio control plane
      serviceAccountName: istiod # Istio's control plane service account
      roleName: istiod-eks-ecs-${CLUSTER_NAME} # Custom IAM role for Istio control plane with ECS access
      permissionPolicyARNs: [arn:aws:iam::aws:policy/AmazonECS_FullAccess]

managedNodeGroups:
  - name: managed-nodes
    instanceType: ${NODE_TYPE} # Instance type defined in variables
    desiredCapacity: ${NUMBER_NODES} # Number of nodes to create
    privateNetworking: true # Ensure nodes are launched within private subnets
    updateConfig:
      maxUnavailable: 2 # Number of nodes that can be updated at the same time
